routes/web.php
<?php

use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\BranchController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DeptsController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\MercatController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ProductCategoryController;
use App\Http\Controllers\ProductCodeController;
use App\Http\Controllers\ProductDesignController;
use App\Http\Controllers\ProductGroupController;
use App\Http\Controllers\ProductPatternController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\UnitController;
use App\Http\Controllers\VendorController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\FieldController;
use App\Http\Controllers\PeriodController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [HomeController::class, 'index'])->name('index');
Route::get('/home', [HomeController::class, 'home'])->name('home');
Route::get('/welcome', [HomeController::class, 'welcome'])->name('welcome');
Route::get('/create', [HomeController::class, 'create'])->name('create'); //ဖျက်ရန်
Route::get('/doc_create', [HomeController::class, 'prepare'])->name('doc_create'); //ဖျက်ရန်
Route::get('/new_code_form', [HomeController::class, 'new_code_form'])->name('new_code_form'); //ဖျက်ရန်


Route::resource('employee', EmployeeController::class);
Route::get('/user_register', [EmployeeController::class, 'register'])->name('user_register');
Route::get('/user_login', [EmployeeController::class, 'login'])->name('user_login');
Route::post('/check_login', [EmployeeController::class, 'check_login'])->name('check_login');
Route::get('/user_reset_pwd', [EmployeeController::class, 'user_reset_pwd'])->name('user_reset_pwd');
Route::post('/reset_pwd', [EmployeeController::class, 'reset_pwd'])->name('reset_pwd');
Route::get('/otp_input', [EmployeeController::class, 'otp_input'])->name('otp_input');
Route::post('/otp_check', [EmployeeController::class, 'otp_check'])->name('otp_check');
Route::get('dept/{id}', [EmployeeController::class, 'getBranch'])->name('get_dept');


Route::get('test', [HomeController::class, 'test'])->name('test');



Auth::routes();


Route::group(['middleware' => ['auth']], function () {

    Route::resource('roles', RoleController::class);
    Route::resource('permissions', PermissionController::class);
    Route::resource('users', UserController::class);
    Route::get('users/branch/{id}', [UserController::class, 'getdept'])->name('get_p_group');
    Route::get('users/create/{id}', [UserController::class, 'getdept'])->name('get_p_group');
 
    Route::get('change_password', [EmployeeController::class, 'change_pwd'])->name('change_pwd');
    Route::patch('update_pwd/{users}', [EmployeeController::class, 'update_pwd'])->name('users.update_pwd');

    Route::resource('brands', BrandController::class);
    Route::resource('branches', BranchController::class);
    Route::resource('suppliers', SupplierController::class);
    Route::resource('depts', DeptsController::class);
    Route::resource('units', UnitController::class);
    Route::resource('mercats', MercatController::class);
    Route::resource('product_Categories', ProductCategoryController::class);
    Route::resource('product_Groups', ProductGroupController::class);
    Route::resource('product_Patterns', ProductPatternController::class);
    Route::resource('product_Designs', ProductDesignController::class);
    Route::resource('product_Codes', ProductCodeController::class);
    Route::resource('documents', DocumentController::class);
    Route::resource('customers', CustomerController::class);
    Route::resource('fields', FieldController::class);
    Route::resource('periods', PeriodController::class);

    // Ajax Category Group Pattern Design

    Route::get('/pcode_generate', [ProductCodeController::class, 'get_pcode_gen'])->name('pcode_generate');
    Route::get('/pcode_man_gen', [ProductCodeController::class, 'pcode_man_gen'])->name('pcode_man_gen');
    Route::post('/pcode_man_get', [ProductCodeController::class, 'pcode_man_get'])->name('pcode_man_get');
    Route::get('product_Codes/cat/{id}', [ProductCodeController::class, 'get_groups'])->name('get_p_group');
    Route::get('product_Codes/gp/{id}', [ProductCodeController::class, 'get_patterns'])->name('get_p_pattern');
    Route::get('product_Codes/ptn/{id}', [ProductCodeController::class, 'get_designs'])->name('get_p_desgin');
    Route::post('product_Codes/nameCheck', [ProductCodeController::class, 'check_name'])->name('check_name');
    Route::get('product_category/{id}', [ProductCodeController::class, 'get_category_by_id'])->name('category_name_by_id');

    // Route::get('/user_register', [EmployeeController::class, 'register'])->name('user_register');
    // Route::get('branches_search', [BranchController::class, 'search'])->name('branches.search');
    Route::get('/admin', [HomeController::class, 'admin'])->name('admin');

    Route::get('/prepare', [HomeController::class, 'prepare'])->name('prepare');
    Route::post('doc_store/{id}', [HomeController::class, 'doc_prepare_save'])->name('doc_store');
    Route::get('prepare_update/{id}', [HomeController::class, 'prepare_update'])->name('prepare_update');
    Route::post('pcode_store', [HomeController::class, 'pcode_store'])->name('pcode_store');
    Route::get('document_view/{id}', [HomeController::class, 'document_view'])->name('document_view');  
    Route::get('/documents_list', [HomeController::class, 'document_list'])->name('documents_list'); 
    Route::get('/document_list', [HomeController::class, 'document_list'])->name('document_list'); // Data table doc list
    Route::get('documents/export/{id}', [DocumentController::class, 'export'])->name('export_excel');
    
    Route::get('/approve', [HomeController::class, 'approve'])->name('approve');
    Route::get('manager_product_codes_edit/{id}', [HomeController::class, 'manager_product_codes_edit'])->name('manager_product_codes_edit');
    Route::post('manager_product_codes_update/{id}', [HomeController::class, 'manager_product_codes_update'])->name('manager_product_codes_update');
    Route::delete('pcode_destory/{id}', [HomeController::class, 'pcode_destory'])->name('pcode_destory');
    Route::get('approve_view/{id}', [HomeController::class, 'approve_view'])->name('approve_view');
    Route::post('approve_store/{id}', [HomeController::class, 'doc_approve_save'])->name('approve_store');
    Route::delete('doc_destory/{id}', [HomeController::class, 'doc_destory'])->name('doc_destory');


    Route::get('/checker', [HomeController::class, 'checker'])->name('checker');
    Route::get('/check/list', [HomeController::class, 'checker_list'])->name('document_list_for_checker');
    Route::post('checked/{id}', [HomeController::class, 'doc_checked_save'])->name('checked');

    Route::get('/approve/list', [HomeController::class, 'manager_list'])->name('document_list_for_manager'); 
    Route::get('/export', [HomeController::class, 'export'])->name('export');
    
    Route::get('/export/list', [HomeController::class, 'sd_list'])->name('document_list_for_SD');
    Route::post('doc_export/{id}', [HomeController::class, 'doc_export'])->name('doc_export');
    Route::get('export_script/{id}', [HomeController::class, 'export_script'])->name('export_script');

    // Route::get('/prepare_update', [HomeController::class, 'index1'])->name('index1');
    Route::post('/autocomplete/fetch', [HomeController::class, 'fetch'])->name('autocomplete.fetch');//Not Use
    Route::post('/autocomplete/vendorfetch', [HomeController::class, 'vendorfetch'])->name('autocomplete.vendorfetch');//Not Use
    Route::post('/autocomplete/brandfetch', [HomeController::class, 'brandfetch'])->name('autocomplete.brandfetch');//Not Use

});

app/Models/Document.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Document extends Model
{
    use HasFactory, SoftDeletes;
    protected $fillable = [
        'document_no',
        'pcode_id',
        'status',
        'prepared_by',
        'prepared_at',
        'checked_at',
        'checked_by',
        'approved_by',
        'approved_at',
        'exported_by',
        'exported_at',
        'deleted_at',
    ];

    public function prepared(){
        return $this->belongsTo(User::class,'prepared_by');
    }
    public function checked(){
        return $this->belongsTo(User::class,'checked_by');
    }
    public function approved(){
        return $this->belongsTo(User::class,'approved_by');
    }
    public function exported(){
     return $this->belongsTo(User::class,'exported_by');
    }
}

app/Http/Controllers/DocumentController.php
<?php

namespace App\Http\Controllers;

use App\Exports\DocumentExport;
use App\Models\Brand;
use App\Models\Document;
use App\Models\Product_Category;
use App\Models\Product_Design;
use App\Models\Product_Group;
use App\Models\Product_Pattern;
use App\Models\ProductCode;
use App\Models\Supplier;
use App\Models\Unit;
use App\Models\User;
use Facade\FlareClient\Http\Response;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use Maatwebsite\Excel\Facades\Excel;

class DocumentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
        $this->middleware('permission:document-list|document-create|document-edit|document-delete', ['only' => ['index', 'show']]);
        $this->middleware('permission:document-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:document-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:document-delete', ['only' => ['destroy']]);
    }
    public function index()
    {
        // $u_id = Auth::id();
        // $u_obj = User::select('mercate_id')->where('id', $u_id)->first();
        // $u_cat = $u_obj->mercate_id;
        // if ($u_cat) {
        //     $category = Product_Category::where('id', $u_cat)->first();
        //     $categories = null;
        // } else {
        //     $categories = Product_Category::query()->get();
        //     $category = null;
        // }
        // $vendors = Supplier::query()->get();
        // $brands = Brand::query()->get();
        // $units = Unit::query()->get();
        // $products = ProductCode::query()->get();
        // return view('documents.index',compact('products','categories', 'category', 'brands', 'vendors', 'units'));
        $documents = Document::query()->get();
        return view('documents.index', compact('documents'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // $u_id = Auth::id();
        // $u_obj = User::select('mercate_id')->where('id', $u_id)->first();
        // $u_cat = $u_obj->mercate_id;
        // if ($u_cat) {
        //     $category = Product_Category::where('id', $u_cat)->first();
        //     $categories = null;
        // } else {
        //     $categories = Product_Category::query()->get();
        //     $category = null;
        // }
        // $vendors = Supplier::query()->get();
        // $brands = Brand::query()->get();
        // $units = Unit::query()->get();
        // return view('documents.create', compact('categories', 'category', 'brands', 'vendors', 'units'));
        return view('documents.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'document_no' => 'required',
            'pcode_id' => 'required',
            'prepared_by' => 'required',
            'approved_by' => 'required',
            'exported_by' => 'required',
            'checked_by' => 'required'
        ]);

        Document::create($request->all());

        return redirect()->route('documents.index')
            ->with('success', 'Document created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Document  $document
     * @return \Illuminate\Http\Response
     */
    public function show(Document $document)
    {
        return view('documents.show', compact('document'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Document  $document
     * @return \Illuminate\Http\Response
     */
    public function edit(Document $document)
    {
        return view('documents.edit', compact('document'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Document  $document
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Document $document)
    {
        request()->validate([
            'document_no' => 'required',
            'pcode_id' => 'required',
            'prepared_by' => 'required',
            'approved_by' => 'required',
            'exported_by' => 'required',
            'checked_at' => 'required',
            'checked_by' => 'required'
        ]);
        $update['document_no'] = $request->get('document_no');
        $update['pcode_id'] = $request->get('pcode_id');
        $update['status'] = $request->get('status');
        $update['prepared_by'] = $request->get('prepared_by');
        $update['prepared_at'] = $request->get('prepared_at');

        $update['checked_at'] = $request->get('checked_at');
        $update['checked_by'] = $request->get('checked_by');
        $update['approved_by'] = $request->get('approved_by');
        $update['approved_at'] = $request->get('approved_at');
        $update['exported_by'] = $request->get('exported_by');
        $update['exported_at'] = $request->get('exported_at');
        
        $document->update($request->all());

        return redirect()->route('documents.index')
            ->with('success', 'Document updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Document  $document
     * @return \Illuminate\Http\Response
     */
    public function destroy(Document $document)
    {
        $document->delete();

        return redirect()->route('documents.index')
            ->with('success', 'Document deleted successfully');
    }
    /////DropdownAjax//////
    public function get_groups($cat_id)
    {
        $data = Product_Group::where('product_category_id', $cat_id)->get();
        // dd($data);
        Log::info($data);
        return response()->json(['data' => $data]);
    }
    public function get_patterns($gp_id)
    {
        $data = Product_Pattern::where('product_group_id', $gp_id)->get();
        // dd($data);
        Log::info($data);
        return response()->json(['data' => $data]);
    }
    public function get_designs($pat_id)
    {
        $data = Product_Design::where('product_pattern_id', $pat_id)->get();
        // dd($data);
        Log::info($data);
        return response()->json(['data' => $data]);
    }

    public function export($doc_id)
    {
        // $this->doc_id = $doc_id;
        $document = Document::find($doc_id); //doc obj of last inserted
        $file_name = $document->document_no;
        // $products = ProductCode::where('doc_no', $this->doc_id)->orderByDesc('id')->paginate(10);
        return Excel::download(new DocumentExport($doc_id), $file_name.'.xlsx');
        // return Response::txt()->with($document);
    }

    // public function getDownload(Request $request){

    //     $logs = Log::all();

    //     $txt = "Logs \n";


    //     foreach ($logs as $log) {
    //         $txt .= $logs->id;
    //         $txt .= "\n";
    //     }

    //     //offer the content of txt as a download (logs.txt)
    //     return response($content)
    //                     ->withHeaders([
    //                         'Content-Type' => 'text/plain',
    //                         'Cache-Control' => 'no-store, no-cache',
    //                         'Content-Disposition' => 'attachment; filename="logs.txt',
    //                     ]);

    //     }


}

resources/views/documents/copy_create.blade.php
@extends('adminlte::page')

@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New Product</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('product_Codes.index') }}"> Back</a>
        </div>
    </div>
</div>
@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif
<form action="{{ route('product_Codes.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="row">
        <div class="offset-xs-10 offset-sm-10  offset-md-10 col-xs-2 col-sm-2 col-md-2">
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Save <i class="fa fab fa-save"></i></button>
            </div>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
                <label class="control-label col-sm-4 pull-left"> Name :</label>

                <input type="text" name="product_name" class="form-control" value="{{ old('product_name') }}" placeholder="Name">
            </div>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
                <label class="control-label col-sm-4 pull-left"> Prodcut Code:</label>
                <input type="text" name="product_code_no" class="form-control" value="{{ old('product_code_no') }}" placeholder="Barcode">
            </div>
        </div>
        <div class="col-xs-4 col-sm-4 col-md-4">
            <div class="form-group">
                <label class="control-label col-sm-4 pull-left"> Product Type <span class="text-red">*</span>:</label>
                <select class="form-control" name="type" required focus>
                    <option value="">{{ '--HIP ? Structure--' }}</option>
                    @if (!empty(old('type')) && old('type') == 0)
                    <option value="0" selected>{{ 'HIP' }}</option>
                    <option value="1">{{ 'STRUCTURE' }}</option>
                    @elseif(!empty(old('type')) && old('type') == 1)
                    <option value="0">{{ 'HIP' }}</option>
                    <option value="1" selected>{{ 'STRUCTURE' }}</option>
                    @else
                    <option value="0">{{ 'HIP' }}</option>
                    <option value="1">{{ 'STRUCTURE' }}</option>
                    @endif
                </select>
            </div>
        </div>
        <div class="col-xs-4 col-sm-4 col-md-4">
            <div class="form-group">
                <label class="control-label col-sm-4 pull-left"> Category Name <span class="text-red">*</span>:</label>
                <select class="form-control" id='category_id' name="{{'category_id'}}" required focus>
                    <option value="">{{ '--Select One Category--' }}</option>
                    @if($categories != null)
                    @foreach ($categories as $ln)
                    <option value="{{$ln->id}}" {{ old('category_id') == $ln->id ? 'selected': '' }}>{{ $ln->product_category_name }}</option>
                    @endforeach
                    @elseif ($category != null)
                    <option value="{{$category->id}}" {{ old('category_id') == $category->id ? 'selected': '' }}>{{ $category->product_category_name }}</option>
                    @endif
                </select>
            </div>
        </div>
        <div class="col-xs-4 col-sm-4 col-md-4">
            <div class="form-group">
                <label class="control-label col-sm-4 pull-left"> Group Name <span class="text-red">*</span>:</label>
                <select class="form-control" id='group_id' name="{{'group_id'}}" required focus>
                    <option value="">{{ '--Select One Group--' }}</option>
                </select>
            </div>
        </div>
        <div class="col-xs-4 col-sm-4 col-md-4">
            <div class="form-group">
                <label class="control-label col-sm-4 pull-left"> Pattern Name <span class="text-red">*</span>:</label>
                <select class="form-control" id='pattern_id' name="{{'pattern_id'}}" required>
                    <option value="">{{ '--Select One Pattern--' }}</option>
                </select>
            </div>
        </div>
        <div class="col-xs-4 col-sm-4 col-md-4">
            <div class="form-group">
                <label class="control-label col-sm-4 pull-left"> Design Name <span class="text-red">*</span>:</label>
                <select class="form-control" id='design_id' name="{{'design_id'}}" required>
                    <option value="">{{ '--Select One Design--' }}</option>
                </select>
            </div>
        </div>
        <div class="col-xs-4 col-sm-4 col-md-4">
            <div class="form-group">
                <label class="control-label col-sm-4 pull-left"> Unit Name <span class="text-red">*</span>:</label>
                <select class="form-control" required name="{{'unit_id'}}" required>
                    <option value="">{{ '--Select One Unit--' }}</option>
                    @foreach ($units as $ln)
                    <option value="{{$ln->id}}">{{ $ln->product_unit_name }}</option>
                    @endforeach
                </select>
            </div>
        </div>
        <div class="col-xs-4 col-sm-4 col-md-4">
            <div class="form-group">
                <label class="control-label col-sm-4 pull-left"> Vendor Name <span class="text-red">*</span>:</label>
                <select class="form-control" name="{{'supplier_id'}}" required>
                    <option value="">{{ '--Select One Vendor--' }}</option>
                    @foreach ($vendors as $ln)
                    <option value="{{$ln->id}}">{{ $ln->vendor_name }}</option>
                    @endforeach
                </select>
            </div>
        </div>
        <div class="col-xs-4 col-sm-4 col-md-4">
            <div class="form-group">
                <label class="control-label col-sm-4 pull-left"> Brand Name <span class="text-red">*</span>:</label>
                <select class="form-control" name="{{'brand_id'}}" required>
                    <option value=""> {{ '--Select One Brand--' }}</option>
                    @foreach ($brands as $ln)
                    <option value="{{$ln->id}}">{{ $ln->product_brand_name }}</option>
                    @endforeach
                </select>
            </div>
        </div>
    </div>
</form>
@endsection

@section('js')
<script type="text/javascript">
    $(document).ready(function() {
        $('#category_id').change(function() {
            var id = $(this).val();
            $('#group_id').find('option').not(':first').remove();
            $.ajax({
                url: 'cat/' + id,
                type: 'get',
                dataType: 'json',
                success: function(response) {
                    var len = 0;
                    if (response.data != null) {
                        len = response.data.length;
                    }
                    if (len > 0) {
                        for (var i = 0; i < len; i++) {
                            var id = response.data[i].product_group_id;
                            var name = response.data[i].product_group_name;
                            // console.log(name);
                            var option = "<option value='" + id + "'>" + name + "</option>";

                            $("#group_id").append(option);
                        }
                    }
                }
            })
        });
        $('#group_id').change(function() {
            var id = $(this).val();
            $('#pattern_id').find('option').not(':first').remove();
            $.ajax({
                url: 'gp/' + id,
                type: 'get',
                dataType: 'json',
                success: function(response) {
                    var len = 0;
                    if (response.data != null) {
                        len = response.data.length;
                    }
                    if (len > 0) {
                        for (var i = 0; i < len; i++) {
                            var id = response.data[i].product_pattern_id;
                            var name = response.data[i].product_pattern_name;
                            // console.log(name);
                            var option = "<option value='" + id + "'>" + name + "</option>";
                            $("#pattern_id").append(option);
                        }
                    }
                }
            })
        });
        $('#pattern_id').change(function() {
            var id = $(this).val();
            $('#design_id').find('option').not(':first').remove();
            $.ajax({
                url: 'ptn/' + id,
                type: 'get',
                dataType: 'json',
                success: function(response) {
                    var len = 0;
                    if (response.data != null) {
                        len = response.data.length;
                    }
                    if (len > 0) {
                        for (var i = 0; i < len; i++) {
                            var id = response.data[i].product_design_id;
                            var name = response.data[i].product_design_name;
                            // console.log(name);
                            var option = "<option value='" + id + "'>" + name + "</option>";
                            $("#design_id").append(option);
                        }
                    }
                }
            })
        });
    });
</script>
@endsection

resources/views/documents/create.blade.php
@extends('adminlte::page')

@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New Product Document</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('documents.index') }}"> Back</a>
        </div>
    </div>
</div>

@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

<form action="{{ route('documents.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Document No:</strong>
                <input type="text" name="document_no" class="form-control" value="{{ old('document_no') }}" placeholder="Document No">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Product Code:</strong>
                <input type="text" name="pcode_id" class="form-control" value="{{ old('pcode_id') }}" placeholder="Product Code">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Status:</strong>
                <input type="text" name="status" class="form-control" value="{{ old('status') }}" placeholder="Status">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Prepare By:</strong>
                <input type="text" name="prepared_by" class="form-control" value="{{ old('prepared_by') }}" placeholder="Prepare By">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Checked At:</strong>
                <input type="text" name="checked_at" class="form-control" value="{{ now() }}" placeholder="Checked At">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Checked By:</strong>
                <input type="text" name="checked_by" class="form-control" value="{{ old('checked_by') }}" placeholder="Checked By">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Prepare At:</strong>
                <input type="text" name="prepared_at" class="form-control" value="{{ now() }}" placeholder="Prepare At">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Approved By:</strong>
                <input type="text" name="approved_by" class="form-control" value="{{ old('approved_by') }}" placeholder="Approved By">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Approved At:</strong>
                <input type="text" name="approved_at" class="form-control" value="{{ now() }}" placeholder="Approved At">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Exported By:</strong>
                <input type="text" name="exported_by" class="form-control" value="{{ old('exported_by') }}" placeholder="Exported By">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Exported At:</strong>
                <input type="text" name="exported_at" class="form-control" value="{{ old('exported_at') }}" placeholder="Exported At">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</form>
@endsection