routes/web.php
<?php

use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\BranchController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DeptsController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\MercatController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ProductCategoryController;
use App\Http\Controllers\ProductCodeController;
use App\Http\Controllers\ProductDesignController;
use App\Http\Controllers\ProductGroupController;
use App\Http\Controllers\ProductPatternController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\UnitController;
use App\Http\Controllers\VendorController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\FieldController;
use App\Http\Controllers\PeriodController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [HomeController::class, 'index'])->name('index');
Route::get('/home', [HomeController::class, 'home'])->name('home');
Route::get('/welcome', [HomeController::class, 'welcome'])->name('welcome');
Route::get('/create', [HomeController::class, 'create'])->name('create'); //ဖျက်ရန်
Route::get('/doc_create', [HomeController::class, 'prepare'])->name('doc_create'); //ဖျက်ရန်
Route::get('/new_code_form', [HomeController::class, 'new_code_form'])->name('new_code_form'); //ဖျက်ရန်


Route::resource('employee', EmployeeController::class);
Route::get('/user_register', [EmployeeController::class, 'register'])->name('user_register');
Route::get('/user_login', [EmployeeController::class, 'login'])->name('user_login');
Route::post('/check_login', [EmployeeController::class, 'check_login'])->name('check_login');
Route::get('/user_reset_pwd', [EmployeeController::class, 'user_reset_pwd'])->name('user_reset_pwd');
Route::post('/reset_pwd', [EmployeeController::class, 'reset_pwd'])->name('reset_pwd');
Route::get('/otp_input', [EmployeeController::class, 'otp_input'])->name('otp_input');
Route::post('/otp_check', [EmployeeController::class, 'otp_check'])->name('otp_check');
Route::get('dept/{id}', [EmployeeController::class, 'getBranch'])->name('get_dept');


Route::get('test', [HomeController::class, 'test'])->name('test');



Auth::routes();


Route::group(['middleware' => ['auth']], function () {

    Route::resource('roles', RoleController::class);
    Route::resource('permissions', PermissionController::class);
    Route::resource('users', UserController::class);
    Route::get('users/branch/{id}', [UserController::class, 'getdept'])->name('get_p_group');
    Route::get('users/create/{id}', [UserController::class, 'getdept'])->name('get_p_group');
 
    Route::get('change_password', [EmployeeController::class, 'change_pwd'])->name('change_pwd');
    Route::patch('update_pwd/{users}', [EmployeeController::class, 'update_pwd'])->name('users.update_pwd');

    Route::resource('brands', BrandController::class);
    Route::resource('branches', BranchController::class);
    Route::resource('suppliers', SupplierController::class);
    Route::resource('depts', DeptsController::class);
    Route::resource('units', UnitController::class);
    Route::resource('mercats', MercatController::class);
    Route::resource('product_Categories', ProductCategoryController::class);
    Route::resource('product_Groups', ProductGroupController::class);
    Route::resource('product_Patterns', ProductPatternController::class);
    Route::resource('product_Designs', ProductDesignController::class);
    Route::resource('product_Codes', ProductCodeController::class);
    Route::resource('documents', DocumentController::class);
    Route::resource('customers', CustomerController::class);
    Route::resource('fields', FieldController::class);
    Route::resource('periods', PeriodController::class);

    // Ajax Category Group Pattern Design

    Route::get('/pcode_generate', [ProductCodeController::class, 'get_pcode_gen'])->name('pcode_generate');
    Route::get('/pcode_man_gen', [ProductCodeController::class, 'pcode_man_gen'])->name('pcode_man_gen');
    Route::post('/pcode_man_get', [ProductCodeController::class, 'pcode_man_get'])->name('pcode_man_get');
    Route::get('product_Codes/cat/{id}', [ProductCodeController::class, 'get_groups'])->name('get_p_group');
    Route::get('product_Codes/gp/{id}', [ProductCodeController::class, 'get_patterns'])->name('get_p_pattern');
    Route::get('product_Codes/ptn/{id}', [ProductCodeController::class, 'get_designs'])->name('get_p_desgin');
    Route::post('product_Codes/nameCheck', [ProductCodeController::class, 'check_name'])->name('check_name');
    Route::get('product_category/{id}', [ProductCodeController::class, 'get_category_by_id'])->name('category_name_by_id');

    // Route::get('/user_register', [EmployeeController::class, 'register'])->name('user_register');
    // Route::get('branches_search', [BranchController::class, 'search'])->name('branches.search');
    Route::get('/admin', [HomeController::class, 'admin'])->name('admin');

    Route::get('/prepare', [HomeController::class, 'prepare'])->name('prepare');
    Route::post('doc_store/{id}', [HomeController::class, 'doc_prepare_save'])->name('doc_store');
    Route::get('prepare_update/{id}', [HomeController::class, 'prepare_update'])->name('prepare_update');
    Route::post('pcode_store', [HomeController::class, 'pcode_store'])->name('pcode_store');
    Route::get('document_view/{id}', [HomeController::class, 'document_view'])->name('document_view');  
    Route::get('/documents_list', [HomeController::class, 'document_list'])->name('documents_list'); 
    Route::get('/document_list', [HomeController::class, 'document_list'])->name('document_list'); // Data table doc list
    Route::get('documents/export/{id}', [DocumentController::class, 'export'])->name('export_excel');
    
    Route::get('/approve', [HomeController::class, 'approve'])->name('approve');
    Route::get('manager_product_codes_edit/{id}', [HomeController::class, 'manager_product_codes_edit'])->name('manager_product_codes_edit');
    Route::post('manager_product_codes_update/{id}', [HomeController::class, 'manager_product_codes_update'])->name('manager_product_codes_update');
    Route::delete('pcode_destory/{id}', [HomeController::class, 'pcode_destory'])->name('pcode_destory');
    Route::get('approve_view/{id}', [HomeController::class, 'approve_view'])->name('approve_view');
    Route::post('approve_store/{id}', [HomeController::class, 'doc_approve_save'])->name('approve_store');
    Route::delete('doc_destory/{id}', [HomeController::class, 'doc_destory'])->name('doc_destory');


    Route::get('/checker', [HomeController::class, 'checker'])->name('checker');
    Route::get('/check/list', [HomeController::class, 'checker_list'])->name('document_list_for_checker');
    Route::post('checked/{id}', [HomeController::class, 'doc_checked_save'])->name('checked');

    Route::get('/approve/list', [HomeController::class, 'manager_list'])->name('document_list_for_manager'); 
    Route::get('/export', [HomeController::class, 'export'])->name('export');
    
    Route::get('/export/list', [HomeController::class, 'sd_list'])->name('document_list_for_SD');
    Route::post('doc_export/{id}', [HomeController::class, 'doc_export'])->name('doc_export');
    Route::get('export_script/{id}', [HomeController::class, 'export_script'])->name('export_script');

    // Route::get('/prepare_update', [HomeController::class, 'index1'])->name('index1');
    Route::post('/autocomplete/fetch', [HomeController::class, 'fetch'])->name('autocomplete.fetch');//Not Use
    Route::post('/autocomplete/vendorfetch', [HomeController::class, 'vendorfetch'])->name('autocomplete.vendorfetch');//Not Use
    Route::post('/autocomplete/brandfetch', [HomeController::class, 'brandfetch'])->name('autocomplete.brandfetch');//Not Use

});

app/Models/Depts.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

use function PHPSTORM_META\map;

class Depts extends Model
{
    use HasFactory, SoftDeletes;
    protected $fillable = [
        'name',
        'branch_id'
    ];
    public function branches(){
        return $this->belongsTo('App\Models\Branch','branch_id');
    }

}

app/Http/Controllers/DeptsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Branch;
use App\Models\Depts;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class DeptsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
        $this->middleware('permission:dept-list|dept-create|dept-edit|dept-delete', ['only' => ['index', 'show']]);
        $this->middleware('permission:dept-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:dept-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:dept-delete', ['only' => ['destroy']]);
    }
    public function index()
    {
        $depts = Depts::latest()->paginate(5);
        return view('depts.index', compact('depts'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    // {pluck('name','name')->
    {
        $branches = Branch::all();
        return view('depts.create', compact('branches'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request);
        request()->validate([
            'name' => 'required',
            'branch_id' => 'required'
        ]);

        Depts::create($request->all());

        return redirect()->route('depts.index')
            ->with('success', 'Department created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Dept  $dept
     * @return \Illuminate\Http\Response
     */
    public function show(Depts $dept)
    {
        return view('depts.show', compact('dept'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Depts  $dept
     * @return \Illuminate\Http\Response
     */
    public function edit(Depts $dept)
    {
        $branches = Branch::all();
        return view('depts.edit', compact('dept', 'branches'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Depts  $dept
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Depts $dept)
    {
        request()->validate([
            'name' => 'required',

        ]);
        $update = [];
        if ($files = $request->file('img')) {
            $destinationPath = 'public/image/'; // upload path
            // $profileImage = date('YmdHis') . "." . $files->getClientOriginalExtension();
            $org_file_name = $files->getClientOriginalName();
            $extension = $files->getClientOriginalExtension();
            $filename = $org_file_name . $extension;
            $files->move($destinationPath, $filename);
            $update['img'] = "$org_file_name";
        }


        $update['name'] = $request->get('name');
        $update['created_by']  = Auth::id();

        $dept->update($request->all());

        return redirect()->route('depts.index')
            ->with('success', 'Department updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Depts  $dept
     * @return \Illuminate\Http\Response
     */
    public function destroy(Depts $dept)
    {
        $dept->delete();

        return redirect()->route('depts.index')
            ->with('success', 'Department deleted successfully');
    }
}

resources/views/depts/create.blade.php
@extends('adminlte::page')

@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New Department</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('depts.index') }}"> Back</a>
        </div>
    </div>
</div>

@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

<form action="{{ route('depts.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Branch Name :</strong>
                <select class="form-control" id="branch_name" name="branch_id" required focus>
                    <option value="" disabled selected>-- Please select branch --</option>
                    @foreach($branches as $branch)
                    <option value="{{$branch->id}}" {{ old('branch_id') == $branch->id ? 'selected': '' }} >{{ $branch->name }}</option>
                    @endforeach                 
                </select>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                <input type="text" name="name" class="form-control" value="{{ old('name') }}" placeholder="Name">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</form>

@endsection

resources/views/depts/edit.blade.php
@extends('adminlte::page')

@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Edit Department</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('depts.index') }}"> Back</a>
        </div>
    </div>
</div>

@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

<form action="{{ route('depts.update',$dept->id) }}" method="POST">
    @csrf
    @method('PUT')
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Branch Name:</strong>
                <select class="form-control" id="branch_name" name="branch_id" required focus>
                    <option value="" disabled selected>-- Please select branch --</option>
                    @foreach($branches as $branch)
                    <option value="{{$branch->id}}" {{ ($branch->id == $dept->branch_id  ? 'selected="selected"' : '') }}>{{ $branch->name }}</option>                 
                    @endforeach
                </select>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                <input type="text" name="name" value="{{ $dept->name }}" class="form-control" placeholder="Name">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</form>
@endsection

resources/views/depts/index.blade.php
@extends('adminlte::page')

@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Departments</h2>
        </div>
        <div class="pull-right mb-3">
            @can('dept-create')
            <a class="btn btn-success" href="{{ route('depts.create') }}"> Add New Department</a>
            @endcan
        </div>
    </div>
</div>

@if ($message = Session::get('success'))
<div class="alert alert-success">
    <p>{{ $message }}</p>
</div>
@endif

<table class="table table-bordered">
    <tr>
        <th>No</th>
        <th>Branch Name</th>
        <th>Dept Name</th>
        <th width="280px">Action</th>
    </tr>
    @foreach ($depts as $dept)
    <tr>
        <td>{{ ++$i }}</td>
        <td>
        {{ isset($dept->branch_id) ? $dept->branches->name: '-'}}</td>
        <td>{{ $dept->name }}</td>
        <td>
            <form action="{{ route('depts.destroy',$dept->id) }}" method="POST">
                <a class="btn btn-info" href="{{ route('depts.show',$dept->id) }}">Show</a>
                @can('dept-edit')
                <a class="btn btn-primary" href="{{ route('depts.edit',$dept->id) }}">Edit</a>
                @endcan
                @csrf
                @method('DELETE')
                @can('dept-delete')
                <button type="submit" class="btn btn-danger">Delete</button>
                @endcan
            </form>
        </td>
    </tr>
    @endforeach
</table>
{!! $depts->links() !!}

@endsection

resources/views/depts/show.blade.php
@extends('adminlte::page')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Department</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('depts.index') }}"> Back</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $dept->name }}
            </div>
        </div>  
    </div>
@endsection