routes/web.php
<?php

use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\BranchController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DeptsController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\MercatController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ProductCategoryController;
use App\Http\Controllers\ProductCodeController;
use App\Http\Controllers\ProductDesignController;
use App\Http\Controllers\ProductGroupController;
use App\Http\Controllers\ProductPatternController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\UnitController;
use App\Http\Controllers\VendorController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\FieldController;
use App\Http\Controllers\PeriodController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [HomeController::class, 'index'])->name('index');
Route::get('/home', [HomeController::class, 'home'])->name('home');
Route::get('/welcome', [HomeController::class, 'welcome'])->name('welcome');
Route::get('/create', [HomeController::class, 'create'])->name('create'); //ဖျက်ရန်
Route::get('/doc_create', [HomeController::class, 'prepare'])->name('doc_create'); //ဖျက်ရန်
Route::get('/new_code_form', [HomeController::class, 'new_code_form'])->name('new_code_form'); //ဖျက်ရန်


Route::resource('employee', EmployeeController::class);
Route::get('/user_register', [EmployeeController::class, 'register'])->name('user_register');
Route::get('/user_login', [EmployeeController::class, 'login'])->name('user_login');
Route::post('/check_login', [EmployeeController::class, 'check_login'])->name('check_login');
Route::get('/user_reset_pwd', [EmployeeController::class, 'user_reset_pwd'])->name('user_reset_pwd');
Route::post('/reset_pwd', [EmployeeController::class, 'reset_pwd'])->name('reset_pwd');
Route::get('/otp_input', [EmployeeController::class, 'otp_input'])->name('otp_input');
Route::post('/otp_check', [EmployeeController::class, 'otp_check'])->name('otp_check');
Route::get('dept/{id}', [EmployeeController::class, 'getBranch'])->name('get_dept');


Route::get('test', [HomeController::class, 'test'])->name('test');



Auth::routes();


Route::group(['middleware' => ['auth']], function () {

    Route::resource('roles', RoleController::class);
    Route::resource('permissions', PermissionController::class);
    Route::resource('users', UserController::class);
    Route::get('users/branch/{id}', [UserController::class, 'getdept'])->name('get_p_group');
    Route::get('users/create/{id}', [UserController::class, 'getdept'])->name('get_p_group');
 
    Route::get('change_password', [EmployeeController::class, 'change_pwd'])->name('change_pwd');
    Route::patch('update_pwd/{users}', [EmployeeController::class, 'update_pwd'])->name('users.update_pwd');

    Route::resource('brands', BrandController::class);
    Route::resource('branches', BranchController::class);
    Route::resource('suppliers', SupplierController::class);
    Route::resource('depts', DeptsController::class);
    Route::resource('units', UnitController::class);
    Route::resource('mercats', MercatController::class);
    Route::resource('product_Categories', ProductCategoryController::class);
    Route::resource('product_Groups', ProductGroupController::class);
    Route::resource('product_Patterns', ProductPatternController::class);
    Route::resource('product_Designs', ProductDesignController::class);
    Route::resource('product_Codes', ProductCodeController::class);
    Route::resource('documents', DocumentController::class);
    Route::resource('customers', CustomerController::class);
    Route::resource('fields', FieldController::class);
    Route::resource('periods', PeriodController::class);

    // Ajax Category Group Pattern Design

    Route::get('/pcode_generate', [ProductCodeController::class, 'get_pcode_gen'])->name('pcode_generate');
    Route::get('/pcode_man_gen', [ProductCodeController::class, 'pcode_man_gen'])->name('pcode_man_gen');
    Route::post('/pcode_man_get', [ProductCodeController::class, 'pcode_man_get'])->name('pcode_man_get');
    Route::get('product_Codes/cat/{id}', [ProductCodeController::class, 'get_groups'])->name('get_p_group');
    Route::get('product_Codes/gp/{id}', [ProductCodeController::class, 'get_patterns'])->name('get_p_pattern');
    Route::get('product_Codes/ptn/{id}', [ProductCodeController::class, 'get_designs'])->name('get_p_desgin');
    Route::post('product_Codes/nameCheck', [ProductCodeController::class, 'check_name'])->name('check_name');
    Route::get('product_category/{id}', [ProductCodeController::class, 'get_category_by_id'])->name('category_name_by_id');

    // Route::get('/user_register', [EmployeeController::class, 'register'])->name('user_register');
    // Route::get('branches_search', [BranchController::class, 'search'])->name('branches.search');
    Route::get('/admin', [HomeController::class, 'admin'])->name('admin');

    Route::get('/prepare', [HomeController::class, 'prepare'])->name('prepare');
    Route::post('doc_store/{id}', [HomeController::class, 'doc_prepare_save'])->name('doc_store');
    Route::get('prepare_update/{id}', [HomeController::class, 'prepare_update'])->name('prepare_update');
    Route::post('pcode_store', [HomeController::class, 'pcode_store'])->name('pcode_store');
    Route::get('document_view/{id}', [HomeController::class, 'document_view'])->name('document_view');  
    Route::get('/documents_list', [HomeController::class, 'document_list'])->name('documents_list'); 
    Route::get('/document_list', [HomeController::class, 'document_list'])->name('document_list'); // Data table doc list
    Route::get('documents/export/{id}', [DocumentController::class, 'export'])->name('export_excel');
    
    Route::get('/approve', [HomeController::class, 'approve'])->name('approve');
    Route::get('manager_product_codes_edit/{id}', [HomeController::class, 'manager_product_codes_edit'])->name('manager_product_codes_edit');
    Route::post('manager_product_codes_update/{id}', [HomeController::class, 'manager_product_codes_update'])->name('manager_product_codes_update');
    Route::delete('pcode_destory/{id}', [HomeController::class, 'pcode_destory'])->name('pcode_destory');
    Route::get('approve_view/{id}', [HomeController::class, 'approve_view'])->name('approve_view');
    Route::post('approve_store/{id}', [HomeController::class, 'doc_approve_save'])->name('approve_store');
    Route::delete('doc_destory/{id}', [HomeController::class, 'doc_destory'])->name('doc_destory');


    Route::get('/checker', [HomeController::class, 'checker'])->name('checker');
    Route::get('/check/list', [HomeController::class, 'checker_list'])->name('document_list_for_checker');
    Route::post('checked/{id}', [HomeController::class, 'doc_checked_save'])->name('checked');

    Route::get('/approve/list', [HomeController::class, 'manager_list'])->name('document_list_for_manager'); 
    Route::get('/export', [HomeController::class, 'export'])->name('export');
    
    Route::get('/export/list', [HomeController::class, 'sd_list'])->name('document_list_for_SD');
    Route::post('doc_export/{id}', [HomeController::class, 'doc_export'])->name('doc_export');
    Route::get('export_script/{id}', [HomeController::class, 'export_script'])->name('export_script');

    // Route::get('/prepare_update', [HomeController::class, 'index1'])->name('index1');
    Route::post('/autocomplete/fetch', [HomeController::class, 'fetch'])->name('autocomplete.fetch');//Not Use
    Route::post('/autocomplete/vendorfetch', [HomeController::class, 'vendorfetch'])->name('autocomplete.vendorfetch');//Not Use
    Route::post('/autocomplete/brandfetch', [HomeController::class, 'brandfetch'])->name('autocomplete.brandfetch');//Not Use

});

resources/views/products/backup.edit.blade.php
@extends('adminlte::page')

@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Edit Product Group</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('product_Codes.index') }}"> Back</a>
        </div>
    </div>
</div>


@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif


<form action="{{ route('product_Codes.update',$product_Code->id) }}" method="POST">
    @csrf
    @method('PUT')

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <label class="control-label col-sm-4 pull-left"> Product Type <span class="text-red">*</span>: </label>
                <select class="form-control" name="type">
                   

                    @if ($product_Code->type == 0)
                    <option value="0" selected>{{ 'HIP' }}</option>
                    <option value="1">{{ 'STRUCTURE' }}</option>
                    @elseif($product_Code->type == 1)
                    <option value="0">{{ 'HIP' }}</option>
                    <option value="1" selected>{{ 'STRUCTURE' }}</option>
                    @else
                    <option value="0">{{ 'HIP' }}</option>
                    <option value="1">{{ 'STRUCTURE' }}</option>
                    @endif
                </select>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Product Code No:</strong>
                <input type="text" name="product_code_no" value="{{ $product_Code->product_code_no }}" class="form-control" placeholder="Product Code No">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Product Name:</strong>
                <input type="text" name="product_name" value="{{ $product_Code->product_name }}" class="form-control" placeholder="Product Name">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <label class="control-label col-sm-4 pull-left"> Category Name <span class="text-red">*</span>:</label>
                <select class="form-control" id='category_id' name="{{'category_id'}}">
                    @if($categories != null)
                    @foreach ($categories as $ln)
                    <option value="{{$ln->id}}" {{ ( $ln->id == $product_Code->category_id  ? 'selected' : '') }}>{{ $ln->product_category_name }}</option>
                    @endforeach
                    @elseif ($category != null)
                    <option value="{{$category->id}}" {{  $product_Code->category_id == $category->id ? 'selected': '' }}>{{ $category->product_category_name }}</option>
                    @endif
                </select>
            </div>

        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <label class="control-label col-sm-4 pull-left"> Group Name <span class="text-red">*</span>:  {{ $product_Code->group_id ? $product_Code->groups->product_group_name  : 'Uncategorized' }} </label>
                <select class="form-control" id='group_id' name="{{'group_id'}}">
                    <option value="0">{{ '--Select One Group--' }}</option>
                   
                </select>
            </div>

        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <label class="control-label col-sm-4 pull-left"> Pattern Name <span class="text-red">*</span>:{{ $product_Code->pattern_id ? $product_Code->patterns->product_pattern_name  : 'Uncategorized' }}</label>
                <select class="form-control" id='pattern_id' name="{{'pattern_id'}}">
                    <option value="0">{{ '--Select One Pattern--' }}</option>
                </select>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <label class="control-label col-sm-4 pull-left"> Design Name <span class="text-red">*</span>:{{ $product_Code->design_id ? $product_Code->designs->product_design_name  : 'Uncategorized' }}</label>
                <select class="form-control" id='design_id' name="{{'design_id'}}">
                    <option value="0">{{ '--Select One Design--' }}</option>

                </select>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <label class="control-label col-sm-4 pull-left"> Unit Name <span class="text-red">*</span>:</label>
                <select class="form-control" name="{{'unit_id'}}">
                    @foreach ($units as $ln)
                    <option value="{{$ln->id}}" {{ ($ln->id == $ln->unit_id  ? 'selected="selected"' : '') }}>{{ $ln->product_unit_name }}</option>
                    @endforeach
                </select>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <label class="control-label col-sm-4 pull-left"> Vendor Name <span class="text-red">*</span>:</label>
                <select class="form-control" name="{{'supplier_id'}}">

                    @foreach ($vendors as $ln)
                    <option value="{{$ln->id}}" {{ ($ln->id == $ln->supplier_id  ? 'selected="selected"' : '') }}> {{ $ln->vendor_name }}</option>
                    @endforeach
                </select>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <label class="control-label col-sm-4 pull-left"> Brand Name <span class="text-red">*</span>:</label>
                <select class="form-control" name="{{'brand_id'}}">
                    @foreach ($brands as $ln)
                    <option value="{{$ln->id}}" {{ ($ln->id == $ln->branch_id  ? 'selected="selected"' : '') }}> {{ $ln->product_brand_name }}</option>
                    @endforeach
                </select>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <label class="control-label col-sm-4 pull-left"> Product Pack Flag<span class="text-red">*</span>: </label>
                <select class="form-control" name="product_pack_flag">
                   

                    @if ($product_Code->product_pack_flag == 0)
                    <option value="0" selected>{{ 'S' }}</option>
                    <option value="1">{{ 'P' }}</option>
                    <option value="2">{{ 'G' }}</option>

                    @elseif($product_Code->product_pack_flag == 1)
                    <option value="0">{{ 'S' }}</option>
                    <option value="1" selected>{{ 'P' }}</option>
                    <option value="2" >{{ 'G' }}</option>
                    @elseif($product_Code->product_pack_flag == 2)
                    <option value="0">{{ 'S' }}</option>
                    <option value="1" >{{ 'P' }}</option>
                    <option value="2" selected>{{ 'G' }}</option>
                    @else
                    <option value="0">{{ 'S' }}</option>
                    <option value="1">{{ 'P' }}</option>
                    <option value="1">{{ 'G' }}</option>

                    @endif
                </select>
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>

</form>


@endsection

@section('js')
<script type="text/javascript">

    $(document).ready(function() {
        var url = window.location.origin;
        $('#category_id').click(function() {
            var id = $(this).val();
            $('#group_id').find('option').not(':first').remove();
            $.ajax({
               
                url: url + '/product_Codes/cat/' + id,
                type: 'get',
                dataType: 'json',
                success: function(response) {
                    var len = 0;
                    if (response.data != null) {
                        len = response.data.length;
                    }

                    if (len > 0) {
                        for (var i = 0; i < len; i++) {
                            var id = response.data[i].product_group_id;
                            var name = response.data[i].product_group_name;
                            // console.log(name);
                            var option = "<option value='" + id + "'>" + name + "</option>";

                            $("#group_id").append(option);
                        }
                    }
                }
            })
        });
        $('#group_id').click(function() {
            var id = $(this).val();
            $('#pattern_id').find('option').not(':first').remove();
            $.ajax({
                url: url + '/product_Codes/gp/' + id,
                type: 'get',
                dataType: 'json',
                success: function(response) {
                    var len = 0;
                    if (response.data != null) {
                        len = response.data.length;
                    }

                    if (len > 0) {
                        for (var i = 0; i < len; i++) {
                            var id = response.data[i].product_pattern_id;
                            var name = response.data[i].product_pattern_name;
                            // console.log(name);
                            var option = "<option value='" + id + "'>" + name + "</option>";
                            $("#pattern_id").append(option);
                        }
                    }
                }
            })
        });
        $('#pattern_id').click(function() {
            var id = $(this).val();
            $('#design_id').find('option').not(':first').remove();
            $.ajax({
                url: url + '/product_Codes/ptn/' + id,
                type: 'get',
                dataType: 'json',
                success: function(response) {
                    var len = 0;
                    if (response.data != null) {
                        len = response.data.length;
                    }

                    if (len > 0) {
                        for (var i = 0; i < len; i++) {
                            var id = response.data[i].product_design_id;
                            var name = response.data[i].product_design_name;
                            // console.log(name);
                            var option = "<option value='" + id + "'>" + name + "</option>";
                            $("#design_id").append(option);
                        }
                    }
                }
            })
        });
    });
</script>
@endsection

resources/views/products/index.blade.php
@extends('adminlte::page')
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Products</h2>
        </div>
        <div class="pull-right mb-3">
            @can('pcode-create')
            <a class="btn btn-success" href="{{ route('product_Codes.create') }}"> Create New Product</a>
            @endcan
        </div>
    </div>
</div>

@if ($message = Session::get('success'))
<div class="alert alert-success">
    <p>{{ $message }}</p>
</div>
@endif

<table class="table table-bordered">
    <tr>
        <th>No</th>
        <th>Type</th>
        <th>Product Code No</th>
        <th>Product Name</th>
        <th>Category</th>
        <th>Group</th>
        <th>Pattern</th>
        <th>Design</th>
        <th>Supplier</th>
        <th>Brand</th>
        <th>Unit</th>
        <th>Product Pack Flag</th>
        <th width="280px">Action</th>
    </tr>
    @foreach ($products as $product)
    <tr>
        <td>{{ ++$i }}</td>
        <td>{{ $product->type === 0 ? 'HIP' : 'Structure' }}</td>
        <td>{{ $product->product_code_no }}</td>
        <td>{{ $product->product_name }}</td>
        <td>{{ $product->category_id ? $product->categories->product_category_name : 'Uncategorized' }}</td>
        <td>{{ $product->group_id ? $product->groups->product_group_name : 'Uncategorized' }}</td>
        <td>{{ $product->pattern_id ? $product->patterns->product_pattern_name : 'Uncategorized' }}</td>
        <td>{{ $product->design_id ? $product->designs->product_design_name : 'Uncategorized' }}</td>
        <td>{{ $product->supplier_id ? $product->suppliers->vendor_name : 'Uncategorized' }}</td>
        <td>{{ $product->brand_id ? $product->brands->product_brand_name : 'Uncategorized' }}</td>
        <td>{{ $product->unit_id ? $product->units->product_unit_name : 'Uncategorized' }}</td>
        <td> @if ($product->product_pack_flag == 0)
            {{ 'G Product Code' }}
            @elseif($product->product_pack_flag == 1)
            {{ 'GP' }}
            @elseif($product->product_pack_flag == 2)
            {{ 'FOC' }}
            @else
            {{ 'S' }}
            {{ 'P' }}
            {{ 'G' }}
            @endif
        </td>
        <td>
            <form action="{{ route('product_Codes.destroy',$product->id) }}" method="POST">
                <a class="btn btn-info" href="{{ route('product_Codes.show',$product->id) }}">Show</a>
                @can('pcode-edit')
                <a class="btn btn-primary" href="{{ route('product_Codes.edit',$product->id) }}">Edit</a>
                @endcan
                @csrf
                @method('DELETE')
                @can('pcode-delete')
                <button type="submit" class="btn btn-danger">Delete</button>
                @endcan
            </form>
        </td>
    </tr>
    @endforeach
</table>
{!! $products->links() !!}

@endsection

resources/views/products/show.blade.php
@extends('adminlte::page')
@section('content')

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2> Product Code</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ URL::previous() }}"> Back</a>
        </div>
    </div>
</div>

@foreach ($products as $product)
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Type:</strong>
            {{ $product_Code->type === 0 ? 'HIP' : 'Structure' }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Product Code No:</strong>
            {{ $product_Code->product_code_no }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Product Name:</strong>
            {{ $product_Code->product_name }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Category:</strong>
            {{ $product_Code->category_id ? $product_Code->categories->product_category_name : 'Uncategorized' }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Group:</strong>
            {{ $product_Code->group_id ? $product_Code->groups->product_group_name : 'Uncategorized' }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Pattern:</strong>
            {{ $product_Code->pattern_id ? $product_Code->patterns->product_pattern_name : 'Uncategorized' }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Design:</strong>
            {{ $product_Code->design_id ? $product_Code->designs->product_design_name : 'Uncategorized' }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Supplier:</strong>
            {{ $product_Code->supplier_id ? $product_Code->suppliers->vendor_name : 'Uncategorized' }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Brand:</strong>
            {{ $product_Code->brand_id ? $product_Code->brands->product_brand_name : 'Uncategorized' }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Unit:</strong>
            {{ $product_Code->unit_id ? $product_Code->units->product_unit_name : 'Uncategorized' }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Product Pack Flag:</strong>
            @if ($product_Code->product_pack_flag == 0)
            {{ 'S' }}
            @elseif($product_Code->product_pack_flag == 1)
            {{ 'P' }}
            @elseif($product_Code->product_pack_flag == 2)
            {{ 'G' }}
            @else
            {{ 'S' }}
            {{ 'P' }}
            {{ 'G' }}
            @endif
        </div>
    </div>
    @endforeach
</div>
@endsection